version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
    ports:
      - 8011:80
